project_id = "tmgcmoghpctzzscjcevz"

[functions.admin-review-driver-application]
verify_jwt = true

[functions.submit-contact-message]
verify_jwt = false

[functions.subscribe-to-journal]
verify_jwt = false

[functions.ai-support-chat]
verify_jwt = true

[functions.expire-rides]
verify_jwt = false
